/*
 *  Group 9
 *  Author: Abdo_203795
 */
package GUIAdmin;

/**
 *
 * @author Abdo_203795
 */
import Person.Admin;
import Station.Station;
import Transportation.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
public class Modify_frame extends javax.swing.JFrame {

    /**
     * Creates new form Modify_frame
     */
    public Admin pa;
     public int id;
    public Modify_frame() 
    {
        initComponents();
    }
    public Modify_frame(Admin pa) 
    {
        this.pa=pa;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        buttonGroupRadioButton = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        Modify_train_route = new javax.swing.JRadioButton();
        Modify_train_time = new javax.swing.JRadioButton();
        Enter_2 = new javax.swing.JButton();
        Back_button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        trainId = new javax.swing.JTextField();

        jButton1.setText("Modify train time slot");

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 441, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 153, 153));

        buttonGroupRadioButton.add(Modify_train_route);
        Modify_train_route.setText("Modify train Route");
        Modify_train_route.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Modify_train_routeActionPerformed(evt);
            }
        });

        buttonGroupRadioButton.add(Modify_train_time);
        Modify_train_time.setText("Modify train time slot");
        Modify_train_time.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Modify_train_timeActionPerformed(evt);
            }
        });

        Enter_2.setText("Enter");
        Enter_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Enter_2ActionPerformed(evt);
            }
        });

        Back_button.setBackground(new java.awt.Color(102, 102, 102));
        Back_button.setText("Back");
        Back_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_buttonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Which modify you want ?");

        jLabel2.setText("Train ID to be modified: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 76, Short.MAX_VALUE)
                .addComponent(Modify_train_route)
                .addGap(67, 67, 67)
                .addComponent(Modify_train_time)
                .addGap(70, 70, 70))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Back_button, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(Enter_2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jLabel2)
                        .addGap(39, 39, 39)
                        .addComponent(trainId, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Modify_train_time)
                    .addComponent(Modify_train_route))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(trainId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(Enter_2)
                .addGap(37, 37, 37)
                .addComponent(Back_button)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Modify_train_routeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Modify_train_routeActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_Modify_train_routeActionPerformed

    private void Modify_train_timeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Modify_train_timeActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_Modify_train_timeActionPerformed

    private void Enter_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Enter_2ActionPerformed
        
        if (trainId.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this, "You must specify which train you want to modify!");
        }
        else
        {
            boolean found = false;
            id = Integer.parseInt(trainId.getText());
            for (Train t: Station.getTrainsList())
            {
                if (t.getId() == id)
                {
                    found = true;
                    break;
                }
            }
            if (found)
            {
                if(Modify_train_route.isSelected())
                {
                   modify_trainRoute F=new modify_trainRoute(pa, id);
                    F.setVisible(true);

                }
                else if (Modify_train_time.isSelected())
                {
                    timeSlot_frame F=new timeSlot_frame(pa, id);
                    F.setVisible(true); 
                }
            }
            else
                JOptionPane.showMessageDialog(this, "No train found with this ID...");
        }
        
    }//GEN-LAST:event_Enter_2ActionPerformed

    private void Back_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_buttonActionPerformed
        // TODO add your handling code here:
        this.toBack();
        HomeAdmin newframe= new  HomeAdmin(pa);
        newframe.setVisible(true);
        newframe.toFront();
        
        
    }//GEN-LAST:event_Back_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Modify_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Modify_frame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back_button;
    private javax.swing.JButton Enter_2;
    private javax.swing.JRadioButton Modify_train_route;
    private javax.swing.JRadioButton Modify_train_time;
    private javax.swing.ButtonGroup buttonGroupRadioButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField trainId;
    // End of variables declaration//GEN-END:variables
}
