/*
 *  Group 9
 *  Author: Amro Sherif 201762
 */
package GUIPassenger;
import Person.Passenger;
import Station.Station;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;

public class ShowAndRemoveBookedTickets extends javax.swing.JFrame {
    private DefaultListModel selectedTicketsModel;
    private DefaultListModel bookedTicketsModel;
    private ArrayList<Integer>passengerSelectedTickets;
    private Passenger currentPassenger;
    private int trainId;
    private int trainIndex;
    private int timeSlot;
    
    public ShowAndRemoveBookedTickets(int trainIndex, int trainId, Passenger currentPassenger, int timeSlot) {
        initComponents();
    
        this.passengerSelectedTickets = new ArrayList<Integer>();
        selectedTicketsModel = new DefaultListModel();
        bookedTicketsModel = new DefaultListModel();
        this.trainIndex = trainIndex;
        this.trainId = trainId;
        this.currentPassenger = currentPassenger;
        this.timeSlot = timeSlot;
        
        ArrayList<String>bookedTickets = currentPassenger.showBookedTicketsOnCertainTrain(trainId, timeSlot);
        for(String i : bookedTickets){
            bookedTicketsModel.addElement(i);
        }
        bookedTicketsList.setModel(bookedTicketsModel);
    }

    private ShowAndRemoveBookedTickets() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header1 = new javax.swing.JLabel();
        bookedTicketsLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        bookedTicketsList = new javax.swing.JList<>();
        submitButton = new javax.swing.JButton();
        previousButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        selectedTicketsList = new javax.swing.JList<>();
        enterSeatNumInput = new javax.swing.JTextField();
        addSeatButton = new javax.swing.JButton();
        enterSeatNumLabel = new javax.swing.JLabel();
        selectedTicketsLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        header1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        header1.setText("Cairo Monorail Ticket booking System");

        bookedTicketsLabel.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        bookedTicketsLabel.setText("These are your booked tickets");

        jScrollPane1.setViewportView(bookedTicketsList);

        submitButton.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        previousButton.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        previousButton.setText("Previous");

        jScrollPane2.setViewportView(selectedTicketsList);

        addSeatButton.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        addSeatButton.setText("Add");
        addSeatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSeatButtonActionPerformed(evt);
            }
        });

        enterSeatNumLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        enterSeatNumLabel.setText("Enter the seat number of the ticket you want to remove");

        selectedTicketsLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        selectedTicketsLabel.setText("Selected tickets");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(selectedTicketsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(addSeatButton)
                        .addGap(148, 148, 148))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(enterSeatNumInput, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(102, 102, 102))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(enterSeatNumLabel)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(147, 147, 147)
                                    .addComponent(header1))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(222, 222, 222)
                                    .addComponent(submitButton)
                                    .addGap(52, 52, 52)
                                    .addComponent(previousButton)))
                            .addGap(133, 133, 133))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 653, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(224, 224, 224)
                        .addComponent(bookedTicketsLabel)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(header1)
                .addGap(13, 13, 13)
                .addComponent(bookedTicketsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(enterSeatNumLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(enterSeatNumInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addSeatButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(selectedTicketsLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitButton)
                    .addComponent(previousButton))
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        for(int i : passengerSelectedTickets){
            currentPassenger.cancelBooking(trainIndex, trainId, i, timeSlot);
        }
        
        try{
            Station.setTrainsList(Station.getTrainsList());
            Station.setPassengersList(Station.getPassengersList());
            JOptionPane.showMessageDialog(null, "Removing is done successfully\n");
            this.dispose();
            new HomePassenger(currentPassenger).setVisible(true);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Cannot access the file to retrieve the data");
        }
    }//GEN-LAST:event_submitButtonActionPerformed

    private void addSeatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSeatButtonActionPerformed
        Integer value = Integer.parseInt(enterSeatNumInput.getText().trim());
        passengerSelectedTickets.add(value);
        
        selectedTicketsModel.addElement(value.toString());
        selectedTicketsList.setModel(selectedTicketsModel);
    }//GEN-LAST:event_addSeatButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShowAndRemoveBookedTickets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShowAndRemoveBookedTickets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShowAndRemoveBookedTickets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShowAndRemoveBookedTickets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShowAndRemoveBookedTickets().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addSeatButton;
    private javax.swing.JLabel bookedTicketsLabel;
    private javax.swing.JList<String> bookedTicketsList;
    private javax.swing.JTextField enterSeatNumInput;
    private javax.swing.JLabel enterSeatNumLabel;
    private javax.swing.JLabel header1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton previousButton;
    private javax.swing.JLabel selectedTicketsLabel;
    private javax.swing.JList<String> selectedTicketsList;
    private javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables
}
