/*
 *  Group 9
 *  Author: 
 */
package GUIPassenger;

import Person.Passenger;
import Station.Station;
import Transportation.Ticket;
import Transportation.Train;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import javafx.util.Pair;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ash
 */
public class ShowPassengerBookedTickets extends javax.swing.JFrame {

    /**
     * Creates new form ShowPassengerBookedTickets
     */
    private Passenger pa;
    private HashMap<Pair<Integer, Integer>, ArrayList<Ticket>> info;
    public ShowPassengerBookedTickets() {
        initComponents();
    }
    public ShowPassengerBookedTickets(Passenger pa) {
        this.pa = pa;
        info = pa.getPassengerTickets();
        initComponents();
        DefaultTableModel model =(DefaultTableModel) displayTable.getModel();
        int row = 0, col;
        for (Map.Entry<Pair<Integer, Integer>, ArrayList<Ticket>> m: info.entrySet())
        {
            col = 0;
            String origin = "", destination = "", bookedTickets = "";
            int timeSlot;
            ArrayList<Ticket> tList;
            Train t = null;
            
            tList = m.getValue();
            if (tList.isEmpty())
                continue;
            
            for (Train currTrain : Station.getTrainsList())
            {
                if (currTrain.getId() == m.getKey().getKey())
                {
                    t = currTrain;
                    break;
                }
            }
            
            origin = t.getRoute().getOrigin();
            destination = t.getRoute().getDestination();
            timeSlot = m.getKey().getValue();
            for (int i = 0 ; i < tList.size() ; i++)
            {
                bookedTickets += tList.get(i).toString() + "\t || ";
            }
            
            model.setValueAt(origin, row, col++);
            model.setValueAt(destination, row, col++);
            model.setValueAt(timeSlot, row, col++);
            model.setValueAt(bookedTickets, row, col);
            row++;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainLabel = new javax.swing.JLabel();
        scrollPaneDT = new javax.swing.JScrollPane();
        displayTable = new javax.swing.JTable();
        back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        mainLabel.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        mainLabel.setText("Your Booked Tickets In All Trains And Timeslots:");

        displayTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Source", "Destination", "Time Slot", "Booked Tickets"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        scrollPaneDT.setViewportView(displayTable);
        if (displayTable.getColumnModel().getColumnCount() > 0) {
            displayTable.getColumnModel().getColumn(0).setMaxWidth(400);
            displayTable.getColumnModel().getColumn(1).setMaxWidth(400);
            displayTable.getColumnModel().getColumn(2).setMaxWidth(100);
        }

        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(mainLabel)
                .addContainerGap(148, Short.MAX_VALUE))
            .addComponent(scrollPaneDT)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(back)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPaneDT, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(back)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        this.dispose();
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShowPassengerBookedTickets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShowPassengerBookedTickets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShowPassengerBookedTickets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShowPassengerBookedTickets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShowPassengerBookedTickets().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JTable displayTable;
    private javax.swing.JLabel mainLabel;
    private javax.swing.JScrollPane scrollPaneDT;
    // End of variables declaration//GEN-END:variables
}
